#!/usr/bin/expect -f
#
# This file is part of Xvisor Build Environment.
# Copyright (C) 2015 Institut de Recherche Technologique SystemX
# Copyright (C) 2015 OpenWide
# All rights reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this Xvisor Build Environment. If not, see
# <http://www.gnu.org/licenses/>.
#
# @file test/xvisor-one-guest-linux-gfx.exp
#

#starts xvisor kick linux guest, run "benchmarks", exit to xvisor and break

set timeout 30

#Assign a variable to the log file

log_file [lindex $argv 0]

#Start the guest VM
global cmd_pid
set cmd_pid [spawn make run QEMU_DISPLAY= ];

#clean on exit
trap {send_error "Test Aborting...\r\n"; exec kill $cmd_pid; exit 1 } { SIGINT }

#Got to xvisor

expect "XVisor# "

send "guest kick guest0\r"
expect "guest0: Kicked"

expect "XVisor# "
send "vserial bind guest0/uart0\r"

expect "basic# "

send "autoexec\r"
expect "Jumping into linux ..."

expect "Please press Enter to activate this console."

#send "\r"

#expect "# "
#send "ls\r"
#expect "# "
#send "ls\r"
#expect "# "

# ESC x q
send "\033xq"

expect "XVisor# "

send "vscreen hard_bind guest0\r"
expect "Frame buffer    : fb0"

sleep 10

#Ctrl-C
send "\003"

expect "qemu: terminating on signal 2"
